"""add crm domain

Revision ID: 0e898a633ce7
Revises: 8d453b823210
Create Date: 2026-09-21 14:35:28.268259
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '0e898a633ce7'
down_revision = '8d453b823210'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_persons_branch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_persons_organization_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons')),
    sa.UniqueConstraint('organization_id', 'phone', name='uq_persons_organization_id_phone')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_persons_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_persons_organization_id_first_name', ['organization_id', 'first_name'], unique=False)
        batch_op.create_index('ix_persons_organization_id_phone', ['organization_id', 'phone'], unique=False)

    op.create_table('saved_searches',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('query_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_saved_searches_branch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_saved_searches_organization_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_searches'))
    )
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_searches_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_searches_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_searches_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_saved_searches_organization_id_is_active', ['organization_id', 'is_active'], unique=False)
        batch_op.create_index('ix_saved_searches_organization_id_user_id', ['organization_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_searches_user_id'), ['user_id'], unique=False)

    op.create_table('customer_requests',
    sa.Column('person_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=True),
    sa.Column('property_type', sa.String(length=32), nullable=True),
    sa.Column('city_code', sa.String(length=8), nullable=True),
    sa.Column('district_code', sa.String(length=8), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('budget_min', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('budget_max', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('area_min', sa.Float(), nullable=True),
    sa.Column('area_max', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('has_parking', sa.Boolean(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('has_warehouse', sa.Boolean(), nullable=True),
    sa.Column('amenities_json', sa.Text(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='active', nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_customer_requests_branch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_customer_requests_organization_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_customer_requests_person_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_requests'))
    )
    with op.batch_alter_table('customer_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_requests_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_requests_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_requests_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_customer_requests_organization_id_person_id', ['organization_id', 'person_id'], unique=False)
        batch_op.create_index('ix_customer_requests_organization_id_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index('ix_customer_requests_organization_id_transaction_type', ['organization_id', 'transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_requests_person_id'), ['person_id'], unique=False)

    op.create_table('favorites',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('property_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_favorites_branch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_favorites_organization_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_favorites_property_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites')),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_favorites_user_id_property_id')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_favorites_organization_id_property_id', ['organization_id', 'property_id'], unique=False)
        batch_op.create_index('ix_favorites_organization_id_user_id', ['organization_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('person_roles',
    sa.Column('person_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_person_roles_branch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_person_roles_organization_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_person_roles_person_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_roles')),
    sa.UniqueConstraint('person_id', 'role', name='uq_person_roles_person_id_role')
    )
    with op.batch_alter_table('person_roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_roles_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_roles_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_roles_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_person_roles_organization_id_person_id', ['organization_id', 'person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_roles_person_id'), ['person_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_roles_person_id'))
        batch_op.drop_index('ix_person_roles_organization_id_person_id')
        batch_op.drop_index(batch_op.f('ix_person_roles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_person_roles_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_person_roles_branch_id'))

    op.drop_table('person_roles')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_property_id'))
        batch_op.drop_index('ix_favorites_organization_id_user_id')
        batch_op.drop_index('ix_favorites_organization_id_property_id')
        batch_op.drop_index(batch_op.f('ix_favorites_organization_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_favorites_branch_id'))

    op.drop_table('favorites')
    with op.batch_alter_table('customer_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_requests_person_id'))
        batch_op.drop_index('ix_customer_requests_organization_id_transaction_type')
        batch_op.drop_index('ix_customer_requests_organization_id_status')
        batch_op.drop_index('ix_customer_requests_organization_id_person_id')
        batch_op.drop_index(batch_op.f('ix_customer_requests_organization_id'))
        batch_op.drop_index(batch_op.f('ix_customer_requests_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_customer_requests_branch_id'))

    op.drop_table('customer_requests')
    with op.batch_alter_table('saved_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_searches_user_id'))
        batch_op.drop_index('ix_saved_searches_organization_id_user_id')
        batch_op.drop_index('ix_saved_searches_organization_id_is_active')
        batch_op.drop_index(batch_op.f('ix_saved_searches_organization_id'))
        batch_op.drop_index(batch_op.f('ix_saved_searches_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_saved_searches_branch_id'))

    op.drop_table('saved_searches')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index('ix_persons_organization_id_phone')
        batch_op.drop_index('ix_persons_organization_id_first_name')
        batch_op.drop_index(batch_op.f('ix_persons_organization_id'))
        batch_op.drop_index(batch_op.f('ix_persons_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_persons_branch_id'))

    op.drop_table('persons')
    # ### end Alembic commands ###
