"""add deals and commission

Revision ID: 30be32e888f7
Revises: 84455b931380
Create Date: 2026-09-21 14:49:59.043474
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '30be32e888f7'
down_revision = '84455b931380'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deals',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('code_period', sa.String(length=16), nullable=False),
    sa.Column('code_sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='lead', nullable=False),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('property_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('agent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('commission_total', sa.BigInteger(), nullable=True),
    sa.Column('commission_agent_share', sa.BigInteger(), nullable=True),
    sa.Column('commission_office_share', sa.BigInteger(), nullable=True),
    sa.Column('commission_referral_share', sa.BigInteger(), nullable=True),
    sa.Column('commission_status', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('loss_reason', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_deals_agent_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_deals_branch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['persons.id'], name=op.f('fk_deals_customer_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_deals_organization_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_deals_property_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_deals_organization_id_code')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_deals_code', ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_deals_organization_id_agent_id', ['organization_id', 'agent_id'], unique=False)
        batch_op.create_index('ix_deals_organization_id_customer_id', ['organization_id', 'customer_id'], unique=False)
        batch_op.create_index('ix_deals_organization_id_property_id', ['organization_id', 'property_id'], unique=False)
        batch_op.create_index('ix_deals_organization_id_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_property_id'), ['property_id'], unique=False)

    op.create_table('deal_status_history',
    sa.Column('deal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('changed_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_deal_status_history_branch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_deal_status_history_deal_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_deal_status_history_organization_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deal_status_history'))
    )
    with op.batch_alter_table('deal_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_status_history_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_status_history_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index('ix_deal_status_history_deal_id_created_at', ['deal_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_status_history_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_status_history_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_deal_status_history_organization_id_deal_id', ['organization_id', 'deal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_status_history', schema=None) as batch_op:
        batch_op.drop_index('ix_deal_status_history_organization_id_deal_id')
        batch_op.drop_index(batch_op.f('ix_deal_status_history_organization_id'))
        batch_op.drop_index(batch_op.f('ix_deal_status_history_is_deleted'))
        batch_op.drop_index('ix_deal_status_history_deal_id_created_at')
        batch_op.drop_index(batch_op.f('ix_deal_status_history_deal_id'))
        batch_op.drop_index(batch_op.f('ix_deal_status_history_branch_id'))

    op.drop_table('deal_status_history')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_property_id'))
        batch_op.drop_index('ix_deals_organization_id_status')
        batch_op.drop_index('ix_deals_organization_id_property_id')
        batch_op.drop_index('ix_deals_organization_id_customer_id')
        batch_op.drop_index('ix_deals_organization_id_agent_id')
        batch_op.drop_index(batch_op.f('ix_deals_organization_id'))
        batch_op.drop_index(batch_op.f('ix_deals_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_deals_customer_id'))
        batch_op.drop_index('ix_deals_code')
        batch_op.drop_index(batch_op.f('ix_deals_branch_id'))
        batch_op.drop_index(batch_op.f('ix_deals_agent_id'))

    op.drop_table('deals')
    # ### end Alembic commands ###
