"""add visits and notifications

Revision ID: 84455b931380
Revises: 0e898a633ce7
Create Date: 2026-09-21 14:44:51.047846
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '84455b931380'
down_revision = '0e898a633ce7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('channel', sa.String(length=32), server_default='in_app', nullable=False),
    sa.Column('priority', sa.String(length=32), server_default='normal', nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('data_json', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_notifications_branch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notifications_organization_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_notifications_organization_id_channel', ['organization_id', 'channel'], unique=False)
        batch_op.create_index('ix_notifications_organization_id_is_read', ['organization_id', 'is_read'], unique=False)
        batch_op.create_index('ix_notifications_organization_id_priority', ['organization_id', 'priority'], unique=False)
        batch_op.create_index('ix_notifications_organization_id_user_id', ['organization_id', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_notifications_user_id_is_read', ['user_id', 'is_read'], unique=False)

    op.create_table('visits',
    sa.Column('property_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('customer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('agent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('visit_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='scheduled', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_notes', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], name=op.f('fk_visits_agent_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_visits_branch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['persons.id'], name=op.f('fk_visits_customer_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_visits_organization_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_visits_property_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visits'))
    )
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_visits_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_visits_organization_id_agent_id', ['organization_id', 'agent_id'], unique=False)
        batch_op.create_index('ix_visits_organization_id_customer_id', ['organization_id', 'customer_id'], unique=False)
        batch_op.create_index('ix_visits_organization_id_date', ['organization_id', 'visit_date'], unique=False)
        batch_op.create_index('ix_visits_organization_id_property_id', ['organization_id', 'property_id'], unique=False)
        batch_op.create_index('ix_visits_organization_id_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_visits_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_visits_property_id'))
        batch_op.drop_index('ix_visits_organization_id_status')
        batch_op.drop_index('ix_visits_organization_id_property_id')
        batch_op.drop_index('ix_visits_organization_id_date')
        batch_op.drop_index('ix_visits_organization_id_customer_id')
        batch_op.drop_index('ix_visits_organization_id_agent_id')
        batch_op.drop_index(batch_op.f('ix_visits_organization_id'))
        batch_op.drop_index(batch_op.f('ix_visits_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_visits_customer_id'))
        batch_op.drop_index(batch_op.f('ix_visits_branch_id'))
        batch_op.drop_index(batch_op.f('ix_visits_agent_id'))

    op.drop_table('visits')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_id_is_read')
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index('ix_notifications_organization_id_user_id')
        batch_op.drop_index('ix_notifications_organization_id_priority')
        batch_op.drop_index('ix_notifications_organization_id_is_read')
        batch_op.drop_index('ix_notifications_organization_id_channel')
        batch_op.drop_index(batch_op.f('ix_notifications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_notifications_branch_id'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
