"""add property domain

Revision ID: 8d453b823210
Revises: 76a44e4e99c4
Create Date: 2026-09-21 14:29:33.632964
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '8d453b823210'
down_revision = '76a44e4e99c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('code_period', sa.String(length=16), nullable=False),
    sa.Column('code_sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_type', sa.String(length=32), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='draft', nullable=False),
    sa.Column('registrant_type', sa.String(length=32), server_default='agent', nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=True),
    sa.Column('owner_phone', sa.String(length=32), nullable=True),
    sa.Column('owner_person_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('land_area', sa.Float(), nullable=True),
    sa.Column('built_area', sa.Float(), nullable=True),
    sa.Column('useful_area', sa.Float(), nullable=True),
    sa.Column('floor_area', sa.Float(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('price', sa.BigInteger(), nullable=True),
    sa.Column('rent_price', sa.BigInteger(), nullable=True),
    sa.Column('deposit', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=8), server_default='IRR', nullable=False),
    sa.Column('is_exchangeable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('exchange_description', sa.Text(), nullable=True),
    sa.Column('owner_share', sa.Float(), nullable=True),
    sa.Column('builder_share', sa.Float(), nullable=True),
    sa.Column('partnership_description', sa.Text(), nullable=True),
    sa.Column('has_parking', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('has_elevator', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('has_warehouse', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('has_balcony', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('amenities_json', sa.Text(), nullable=True),
    sa.Column('legal_info', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_properties_branch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_properties_organization_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties')),
    sa.UniqueConstraint('organization_id', 'code', name='uq_properties_organization_id_code')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index('ix_properties_code', ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_properties_organization_id_property_type', ['organization_id', 'property_type'], unique=False)
        batch_op.create_index('ix_properties_organization_id_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index('ix_properties_organization_id_transaction_type', ['organization_id', 'transaction_type'], unique=False)
        batch_op.create_index('ix_properties_property_type', ['property_type'], unique=False)
        batch_op.create_index('ix_properties_status', ['status'], unique=False)
        batch_op.create_index('ix_properties_transaction_type', ['transaction_type'], unique=False)

    op.create_table('property_locations',
    sa.Column('property_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('city_code', sa.String(length=8), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('district_code', sa.String(length=8), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('public_lat', sa.Float(), nullable=True),
    sa.Column('public_lng', sa.Float(), nullable=True),
    sa.Column('exact_address', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_property_locations_branch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_property_locations_organization_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_locations_property_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_locations')),
    sa.UniqueConstraint('property_id', name='uq_property_locations_property_id')
    )
    with op.batch_alter_table('property_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_locations_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_locations_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_locations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_property_locations_organization_id_city_code', ['organization_id', 'city_code'], unique=False)
        batch_op.create_index('ix_property_locations_organization_id_district_code', ['organization_id', 'district_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_locations_property_id'), ['property_id'], unique=False)

    op.create_table('property_media',
    sa.Column('property_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=200), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('storage_backend', sa.String(length=20), server_default='filesystem', nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_property_media_branch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_property_media_organization_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_media_property_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_media'))
    )
    with op.batch_alter_table('property_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_media_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_media_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_media_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_property_media_organization_id_property_id', ['organization_id', 'property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_media_property_id'), ['property_id'], unique=False)
        batch_op.create_index('ix_property_media_property_id_sort_order', ['property_id', 'sort_order'], unique=False)

    op.create_table('property_usages',
    sa.Column('property_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('usage_type', sa.String(length=32), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('organization_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('branch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('updated_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_property_usages_branch_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_property_usages_organization_id'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_usages_property_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_usages')),
    sa.UniqueConstraint('property_id', 'usage_type', name='uq_property_usages_property_id_usage_type')
    )
    with op.batch_alter_table('property_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_usages_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_usages_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_usages_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_property_usages_organization_id_property_id', ['organization_id', 'property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_usages_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_usages_property_id'))
        batch_op.drop_index('ix_property_usages_organization_id_property_id')
        batch_op.drop_index(batch_op.f('ix_property_usages_organization_id'))
        batch_op.drop_index(batch_op.f('ix_property_usages_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_property_usages_branch_id'))

    op.drop_table('property_usages')
    with op.batch_alter_table('property_media', schema=None) as batch_op:
        batch_op.drop_index('ix_property_media_property_id_sort_order')
        batch_op.drop_index(batch_op.f('ix_property_media_property_id'))
        batch_op.drop_index('ix_property_media_organization_id_property_id')
        batch_op.drop_index(batch_op.f('ix_property_media_organization_id'))
        batch_op.drop_index(batch_op.f('ix_property_media_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_property_media_branch_id'))

    op.drop_table('property_media')
    with op.batch_alter_table('property_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_locations_property_id'))
        batch_op.drop_index('ix_property_locations_organization_id_district_code')
        batch_op.drop_index('ix_property_locations_organization_id_city_code')
        batch_op.drop_index(batch_op.f('ix_property_locations_organization_id'))
        batch_op.drop_index(batch_op.f('ix_property_locations_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_property_locations_branch_id'))

    op.drop_table('property_locations')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index('ix_properties_transaction_type')
        batch_op.drop_index('ix_properties_status')
        batch_op.drop_index('ix_properties_property_type')
        batch_op.drop_index('ix_properties_organization_id_transaction_type')
        batch_op.drop_index('ix_properties_organization_id_status')
        batch_op.drop_index('ix_properties_organization_id_property_type')
        batch_op.drop_index(batch_op.f('ix_properties_organization_id'))
        batch_op.drop_index(batch_op.f('ix_properties_is_deleted'))
        batch_op.drop_index('ix_properties_code')
        batch_op.drop_index(batch_op.f('ix_properties_branch_id'))

    op.drop_table('properties')
    # ### end Alembic commands ###
